export type Domain =
  | "business"
  | "career"
  | "relationships"
  | "dating"
  | "lifestyle"
  | "random";

export type SparkPrompt = {
  id: string;
  domain: Domain;
  text: string;
  intensity?: "low" | "medium" | "high";
  tags?: string[];
};

export const sparkConstraints = [
  "15 minutes only",
  "10-minute timer",
  "limit to 3 items",
  "one pass only",
  "no new tools",
  "no money spent",
  "before lunch",
  "before dinner",
  "keep it to 5 bullets",
  "no phone",
  "stop at 20 minutes",
  "do it in one sitting",
];

export const sparkLibrary: Record<Domain, SparkPrompt[]> = {
  business: [
    { id: "business-001", domain: "business", text: "Rewrite your pricing page headline to name the specific outcome." },
    { id: "business-002", domain: "business", text: "List the top 5 objections from recent sales calls." },
    { id: "business-003", domain: "business", text: "Draft a 3-step onboarding email sequence." },
    { id: "business-004", domain: "business", text: "Pick one churned customer and write why they left." },
    { id: "business-005", domain: "business", text: "Create a one-sentence offer for your homepage hero." },
    { id: "business-006", domain: "business", text: "Outline a 5-slide product demo flow." },
    { id: "business-007", domain: "business", text: "Review the last 10 support tickets and tag the top theme." },
    { id: "business-008", domain: "business", text: "Write a follow-up email to a stalled lead." },
    { id: "business-009", domain: "business", text: "Define success metrics for your next experiment." },
    { id: "business-010", domain: "business", text: "Trim one step from your checkout flow." },
    { id: "business-011", domain: "business", text: "Map the first 3 minutes of user activation." },
    { id: "business-012", domain: "business", text: "Update your FAQ with the most common pre-sale question." },
    { id: "business-013", domain: "business", text: "Write a short case study intro for a happy customer." },
    { id: "business-014", domain: "business", text: "Identify one upsell opportunity in your current plan." },
    { id: "business-015", domain: "business", text: "Draft a weekly pipeline review checklist." },
    { id: "business-016", domain: "business", text: "Create a simple win-back message for past customers." },
    { id: "business-017", domain: "business", text: "Sketch a 2-minute product walkthrough script." },
    { id: "business-018", domain: "business", text: "List the top 3 referral sources from this month." },
    { id: "business-019", domain: "business", text: "Write a clear refund policy sentence." },
    { id: "business-020", domain: "business", text: "Decide the next pricing test you will run." },
    { id: "business-021", domain: "business", text: "Summarize your product in 10 words." },
    { id: "business-022", domain: "business", text: "Pick one feature to de-emphasize on your website." },
    { id: "business-023", domain: "business", text: "Write the opening line for a partner outreach email." },
    { id: "business-024", domain: "business", text: "Choose one KPI to review every Monday." },
    { id: "business-025", domain: "business", text: "Draft a checklist for first-time setup." },
    { id: "business-026", domain: "business", text: "Write a one-paragraph 'who this is for / not for' statement.", intensity: "low", tags: ["positioning","clarity"] },
  { id: "business-027", domain: "business", text: "List 10 feature requests you should say no to (and why).", intensity: "medium", tags: ["product","focus"] },
  { id: "business-028", domain: "business", text: "Rewrite your offer so the first line includes a timeframe (e.g. 'in 14 days').", intensity: "low", tags: ["offer","copy"] },
  { id: "business-029", domain: "business", text: "Draft a 'last chance' email for a trial expiring tomorrow.", intensity: "low", tags: ["email","conversion"] },
  { id: "business-030", domain: "business", text: "Write a 5-bullet competitor comparison that stays honest and calm.", intensity: "medium", tags: ["positioning","competition"] },
  { id: "business-031", domain: "business", text: "Pick one onboarding step and remove friction: fewer fields, fewer clicks, fewer words.", intensity: "medium", tags: ["ux","activation"] },
  { id: "business-032", domain: "business", text: "Turn one support reply into a reusable macro/template.", intensity: "low", tags: ["support","ops"] },
  { id: "business-033", domain: "business", text: "Create a list of 12 content topics your customers already ask about.", intensity: "medium", tags: ["content","research"] },
  { id: "business-034", domain: "business", text: "Write a one-sentence value prop for each pricing tier.", intensity: "low", tags: ["pricing","copy"] },
  { id: "business-035", domain: "business", text: "Draft a simple 'How we work' section for your site.", intensity: "low", tags: ["trust","website"] },
  { id: "business-036", domain: "business", text: "Pick one churn reason and design a single prevention experiment.", intensity: "high", tags: ["retention","experiment"] },
  { id: "business-037", domain: "business", text: "Write the script for a 30-second Loom demo of your core feature.", intensity: "medium", tags: ["demo","sales"] },
  { id: "business-038", domain: "business", text: "List your top 5 customer types and rank them by profit + joy.", intensity: "medium", tags: ["strategy","focus"] },
  { id: "business-039", domain: "business", text: "Write a 'pricing anchor' paragraph explaining why it costs what it costs.", intensity: "medium", tags: ["pricing","trust"] },
  { id: "business-040", domain: "business", text: "Create a 5-question customer interview guide you can run this week.", intensity: "medium", tags: ["research","customer"] },
  { id: "business-041", domain: "business", text: "Write a single KPI dashboard definition: metrics, source, cadence, owner.", intensity: "high", tags: ["ops","metrics"] },
  { id: "business-042", domain: "business", text: "Pick one channel you're ignoring and write the first outreach message.", intensity: "medium", tags: ["growth","outreach"] },
  { id: "business-043", domain: "business", text: "Draft a 'pause subscription' option message that keeps dignity (no guilt).", intensity: "low", tags: ["retention","copy"] },
  { id: "business-044", domain: "business", text: "Make a 10-item checklist for what 'ship' means in your product.", intensity: "high", tags: ["delivery","quality"] },
  { id: "business-045", domain: "business", text: "Write 3 alternative CTAs for your main button (not 'Get started').", intensity: "low", tags: ["copy","conversion"] },
  { id: "business-046", domain: "business", text: "Pick one bottleneck in fulfilment and design a 1-hour fix.", intensity: "medium", tags: ["ops","process"] },
  { id: "business-047", domain: "business", text: "Draft a referral ask message that feels personal (not salesy).", intensity: "low", tags: ["referrals","copy"] },
  { id: "business-048", domain: "business", text: "Write a one-paragraph 'why now' narrative for your product.", intensity: "medium", tags: ["story","positioning"] },
  { id: "business-049", domain: "business", text: "List 10 reasons people don’t buy and circle the top 2 that are fixable this week.", intensity: "high", tags: ["conversion","diagnosis"] },
  { id: "business-050", domain: "business", text: "Create a 'first 10 customers' plan: who, where, message, proof.", intensity: "high", tags: ["sales","plan"] },
  { id: "business-051", domain: "business", text: "Write a small guarantee that reduces risk without overpromising.", intensity: "medium", tags: ["trust","offer"] },
  { id: "business-052", domain: "business", text: "Rewrite one confusing UI label into plain English.", intensity: "low", tags: ["ux","copy"] },
  { id: "business-053", domain: "business", text: "Make a list of features you can delete or hide for simplicity.", intensity: "medium", tags: ["product","simplicity"] },
  { id: "business-054", domain: "business", text: "Write the one sentence you want a customer to tell a friend.", intensity: "low", tags: ["positioning","word-of-mouth"] },
  { id: "business-055", domain: "business", text: "Draft a pricing objection reply in 3 lines: empathise, reframe, next step.", intensity: "low", tags: ["sales","objections"] },
  { id: "business-056", domain: "business", text: "Create a list of 20 brand words: 10 'we are', 10 'we are not'.", intensity: "medium", tags: ["brand","clarity"] },
  { id: "business-057", domain: "business", text: "Choose one metric to stop tracking because it distracts you.", intensity: "low", tags: ["focus","metrics"] },
  { id: "business-058", domain: "business", text: "Write an internal 'definition of done' for support tickets.", intensity: "medium", tags: ["support","ops"] },
  { id: "business-059", domain: "business", text: "Turn your last customer complaint into a one-sentence product principle.", intensity: "medium", tags: ["product","learning"] },
  { id: "business-060", domain: "business", text: "Draft a one-page 'press kit' outline: bio, screenshots, links, story.", intensity: "high", tags: ["marketing","assets"] },
  { id: "business-061", domain: "business", text: "Write 5 interview questions to validate demand before building.", intensity: "medium", tags: ["validation","research"] },
  { id: "business-062", domain: "business", text: "Write an 'if this then that' escalation guide for customer issues.", intensity: "high", tags: ["support","process"] },
  { id: "business-063", domain: "business", text: "Create a 7-day mini challenge customers can do using your product.", intensity: "high", tags: ["engagement","retention"] },
  { id: "business-064", domain: "business", text: "List 5 trust elements to add to your website this week.", intensity: "medium", tags: ["trust","website"] },
  { id: "business-065", domain: "business", text: "Write a 'this is for busy people' onboarding path in 3 steps.", intensity: "medium", tags: ["onboarding","simplicity"] },

  ],
  career: [
    { id: "career-001", domain: "career", text: "Add one quantified impact bullet to your resume." },
    { id: "career-002", domain: "career", text: "Write a two-sentence update for your manager." },
    { id: "career-003", domain: "career", text: "List three projects that show your strongest skills." },
    { id: "career-004", domain: "career", text: "Draft a short ask for feedback on your last project." },
    { id: "career-005", domain: "career", text: "Outline a promotion case with three outcomes you drove." },
    { id: "career-006", domain: "career", text: "Update your LinkedIn headline to match your target role." },
    { id: "career-007", domain: "career", text: "Identify one skill gap and a concrete next step to close it." },
    { id: "career-008", domain: "career", text: "Write a one-paragraph summary of a recent win." },
    { id: "career-009", domain: "career", text: "Create a one-page portfolio outline." },
    { id: "career-010", domain: "career", text: "Send a thank-you note to a mentor or teammate." },
    { id: "career-011", domain: "career", text: "Draft a meeting agenda for your next 1:1." },
    { id: "career-012", domain: "career", text: "List the top five companies you want to work for." },
    { id: "career-013", domain: "career", text: "Write a concise intro for a networking request." },
    { id: "career-014", domain: "career", text: "Review your calendar and block a focus window." },
    { id: "career-015", domain: "career", text: "Capture three metrics you can report in your next update." },
    { id: "career-016", domain: "career", text: "Draft a short story about solving a hard problem at work." },
    { id: "career-017", domain: "career", text: "Pick one project to de-scope and define the smaller win." },
    { id: "career-018", domain: "career", text: "Write a brief post about a lesson learned on the job." },
    { id: "career-019", domain: "career", text: "Create a checklist for your weekly review." },
    { id: "career-020", domain: "career", text: "List three people you should keep updated this week." },
    { id: "career-021", domain: "career", text: "Update one portfolio screenshot or case study image." },
    { id: "career-022", domain: "career", text: "Write a one-line summary of your current role." },
    { id: "career-023", domain: "career", text: "Draft a cold outreach note to a recruiter." },
    { id: "career-024", domain: "career", text: "Define success criteria for your next deliverable." },
    { id: "career-025", domain: "career", text: "List three meetings you can decline or shorten." },
    { id: "career-026", domain: "career", text: "Write a 'brag doc' entry for one win this week (facts only).", intensity: "low", tags: ["tracking","growth"] },
  { id: "career-027", domain: "career", text: "List 3 tasks you do that should be automated or delegated.", intensity: "medium", tags: ["efficiency","ops"] },
  { id: "career-028", domain: "career", text: "Draft a one-sentence career narrative: 'I help X do Y by Z.'", intensity: "low", tags: ["positioning","clarity"] },
  { id: "career-029", domain: "career", text: "Pick one meeting you attend and propose a shorter format.", intensity: "medium", tags: ["communication","efficiency"] },
  { id: "career-030", domain: "career", text: "Write a list of your top 10 repeatable strengths.", intensity: "low", tags: ["self-awareness","strengths"] },
  { id: "career-031", domain: "career", text: "Identify one relationship at work you should repair and draft the opener.", intensity: "high", tags: ["relationships","communication"] },
  { id: "career-032", domain: "career", text: "Write a 5-bullet 'what I’m working on' update for stakeholders.", intensity: "low", tags: ["stakeholders","comms"] },
  { id: "career-033", domain: "career", text: "Make a 3-month learning plan for one skill: resources + practice + proof.", intensity: "high", tags: ["learning","plan"] },
  { id: "career-034", domain: "career", text: "Draft a template for meeting notes you will reuse every time.", intensity: "low", tags: ["systems","notes"] },
  { id: "career-035", domain: "career", text: "Write a two-line thank you to someone who unblocked you recently.", intensity: "low", tags: ["gratitude","relationships"] },
  { id: "career-036", domain: "career", text: "List the top 5 'career bets' you could make this year.", intensity: "medium", tags: ["strategy","planning"] },
  { id: "career-037", domain: "career", text: "Define the one thing you want to be known for at work.", intensity: "medium", tags: ["brand","focus"] },
  { id: "career-038", domain: "career", text: "Write a short 'handover note' for a project (even if it’s not ending).", intensity: "medium", tags: ["quality","ops"] },
  { id: "career-039", domain: "career", text: "Draft your ideal role as a job ad (responsibilities + outcomes).", intensity: "high", tags: ["vision","career"] },
  { id: "career-040", domain: "career", text: "Pick one messy doc/process and rewrite it in plain English.", intensity: "medium", tags: ["clarity","docs"] },
  { id: "career-041", domain: "career", text: "Write 3 example STAR stories you can reuse in interviews.", intensity: "high", tags: ["interview","prep"] },
  { id: "career-042", domain: "career", text: "Create a list of 10 people you admire and what you can copy (ethically).", intensity: "medium", tags: ["learning","role-models"] },
  { id: "career-043", domain: "career", text: "Write a one-paragraph 'my working style' note.", intensity: "low", tags: ["comms","self-awareness"] },
  { id: "career-044", domain: "career", text: "Identify one KPI you own and define how you'll improve it by 5%.", intensity: "high", tags: ["impact","metrics"] },
  { id: "career-045", domain: "career", text: "Draft a conflict de-escalation line you can use in tense meetings.", intensity: "medium", tags: ["comms","conflict"] },
  { id: "career-046", domain: "career", text: "Write a 5-bullet 'what success looks like' for your current project.", intensity: "medium", tags: ["clarity","delivery"] },
  { id: "career-047", domain: "career", text: "Pick one internal process that wastes time and propose a fix.", intensity: "high", tags: ["ops","improvement"] },
  { id: "career-048", domain: "career", text: "Draft a concise message asking for more responsibility (with examples).", intensity: "high", tags: ["growth","ask"] },
  { id: "career-049", domain: "career", text: "List 5 achievements to bring up in your next performance conversation.", intensity: "medium", tags: ["performance","prep"] },
  { id: "career-050", domain: "career", text: "Write a one-page case study outline for your best project.", intensity: "high", tags: ["portfolio","proof"] },
  { id: "career-051", domain: "career", text: "Set a boundary for after-hours work and draft how you'll communicate it.", intensity: "high", tags: ["boundaries","health"] },
  { id: "career-052", domain: "career", text: "Pick one recurring problem and write the 'root cause in one sentence'.", intensity: "medium", tags: ["problem-solving","clarity"] },
  { id: "career-053", domain: "career", text: "Write a one-line summary for each tool you use daily (and why).", intensity: "low", tags: ["systems","workflow"] },
  { id: "career-054", domain: "career", text: "Draft a 'quick status' Slack/Teams update template.", intensity: "low", tags: ["comms","templates"] },
  { id: "career-055", domain: "career", text: "Write a list of 'career rules' you want to live by.", intensity: "medium", tags: ["values","direction"] },
  { id: "career-056", domain: "career", text: "Create a 'weekend reset' checklist for Monday-you.", intensity: "low", tags: ["planning","systems"] },
  { id: "career-057", domain: "career", text: "Pick one newsletter/podcast that helps your role and commit to one episode.", intensity: "low", tags: ["learning","habits"] },
  { id: "career-058", domain: "career", text: "Write a short ask to shadow someone for 30 minutes.", intensity: "medium", tags: ["learning","networking"] },
  { id: "career-059", domain: "career", text: "List 3 risks for your current work and how you're mitigating them.", intensity: "medium", tags: ["risk","delivery"] },
  { id: "career-060", domain: "career", text: "Draft a 'handoff message' for when you're away (clarity saves everyone).", intensity: "medium", tags: ["ops","comms"] },
  { id: "career-061", domain: "career", text: "Write a concise 'why I'm a fit' paragraph for your target job.", intensity: "high", tags: ["applications","copy"] },
  { id: "career-062", domain: "career", text: "Pick one thing you’re avoiding and schedule it for a specific time.", intensity: "medium", tags: ["execution","planning"] },
  { id: "career-063", domain: "career", text: "Write down your top 3 'energy leaks' at work and one fix for each.", intensity: "medium", tags: ["health","efficiency"] },
  { id: "career-064", domain: "career", text: "Draft your 'tell me about yourself' answer in 5 sentences.", intensity: "high", tags: ["interview","prep"] },
  { id: "career-065", domain: "career", text: "List 5 decisions you can make faster by setting a rule.", intensity: "medium", tags: ["decision-making","systems"] },

  ],
  relationships: [
    { id: "relationships-001", domain: "relationships", text: "Ask your partner what would make next week easier." },
    { id: "relationships-002", domain: "relationships", text: "Send a short appreciation text to a close friend." },
    { id: "relationships-003", domain: "relationships", text: "Plan a low-key hangout with someone you miss." },
    { id: "relationships-004", domain: "relationships", text: "Write down one recurring tension and a gentle opener." },
    { id: "relationships-005", domain: "relationships", text: "Set a shared calendar reminder for a weekly check-in." },
    { id: "relationships-006", domain: "relationships", text: "Ask a family member how you can support them this month." },
    { id: "relationships-007", domain: "relationships", text: "Share one thing you appreciated about today." },
    { id: "relationships-008", domain: "relationships", text: "Name one small household task you will take over." },
    { id: "relationships-009", domain: "relationships", text: "Write a short apology note for a recent misstep." },
    { id: "relationships-010", domain: "relationships", text: "Bring up one decision that needs alignment soon." },
    { id: "relationships-011", domain: "relationships", text: "Plan a device-free meal with someone you live with." },
    { id: "relationships-012", domain: "relationships", text: "Ask a friend a question you have been avoiding." },
    { id: "relationships-013", domain: "relationships", text: "Choose one boundary you need to restate clearly." },
    { id: "relationships-014", domain: "relationships", text: "Send a simple \"thinking-of-you\" text to someone important." },
    { id: "relationships-015", domain: "relationships", text: "Schedule a short walk-and-talk with your partner." },
    { id: "relationships-016", domain: "relationships", text: "Write down one shared goal for the next month." },
    { id: "relationships-017", domain: "relationships", text: "Ask for clarification instead of assuming intent." },
    { id: "relationships-018", domain: "relationships", text: "Offer help on a task your roommate dislikes." },
    { id: "relationships-019", domain: "relationships", text: "Share one story about your day that invites response." },
    { id: "relationships-020", domain: "relationships", text: "Plan a low-cost activity you both enjoy." },
    { id: "relationships-021", domain: "relationships", text: "Write down one thing you want to celebrate together." },
    { id: "relationships-022", domain: "relationships", text: "Invite feedback on how you can communicate better." },
    { id: "relationships-023", domain: "relationships", text: "Pick one conversation to follow up on this week." },
    { id: "relationships-024", domain: "relationships", text: "Send a quick voice note to check in with a friend." },
    { id: "relationships-025", domain: "relationships", text: "Make a plan to reconnect with someone you drifted from." },
     { id: "relationships-026", domain: "relationships", text: "Ask: 'What’s one thing you want more of from me lately?'", intensity: "medium", tags: ["communication","check-in"] },
  { id: "relationships-027", domain: "relationships", text: "Plan a 15-minute weekly reset chat (same time each week).", intensity: "medium", tags: ["systems","routine"] },
  { id: "relationships-028", domain: "relationships", text: "Write a list of 5 ways you show love, then ask theirs.", intensity: "medium", tags: ["connection","clarity"] },
  { id: "relationships-029", domain: "relationships", text: "Send a message that names a specific moment you appreciated.", intensity: "low", tags: ["gratitude","connection"] },
  { id: "relationships-030", domain: "relationships", text: "Pick one small promise you can keep this week (and keep it).", intensity: "medium", tags: ["trust","actions"] },
  { id: "relationships-031", domain: "relationships", text: "Ask someone close: 'Anything I’ve been missing lately?'", intensity: "high", tags: ["feedback","growth"] },
  { id: "relationships-032", domain: "relationships", text: "Make a plan for one shared activity you both actually enjoy.", intensity: "low", tags: ["fun","planning"] },
  { id: "relationships-033", domain: "relationships", text: "Write a calm opener for a hard convo: 'Can we talk about X, no blame?'", intensity: "high", tags: ["conflict","communication"] },
  { id: "relationships-034", domain: "relationships", text: "Do one household task without being asked (quiet competence).", intensity: "low", tags: ["actions","care"] },
  { id: "relationships-035", domain: "relationships", text: "Ask: 'What would make today feel like a win for you?'", intensity: "low", tags: ["support","presence"] },
  { id: "relationships-036", domain: "relationships", text: "Write down one boundary you need and how you’ll say it kindly.", intensity: "high", tags: ["boundaries","clarity"] },
  { id: "relationships-037", domain: "relationships", text: "Plan a no-phone 30-minute time block together.", intensity: "medium", tags: ["presence","connection"] },
  { id: "relationships-038", domain: "relationships", text: "Send a 10-second voice note instead of texting (more human).", intensity: "low", tags: ["connection","effort"] },
  { id: "relationships-039", domain: "relationships", text: "Write one apology that avoids excuses: impact, ownership, fix.", intensity: "high", tags: ["repair","communication"] },
  { id: "relationships-040", domain: "relationships", text: "Make a list: 'What we’re doing well' (3 things) and share it.", intensity: "medium", tags: ["positive","growth"] },
  { id: "relationships-041", domain: "relationships", text: "Ask: 'What’s something I could do that would feel supportive?'", intensity: "medium", tags: ["support","check-in"] },
  { id: "relationships-042", domain: "relationships", text: "Pick a recurring argument and name the pattern (not the person).", intensity: "high", tags: ["conflict","pattern"] },
  { id: "relationships-043", domain: "relationships", text: "Schedule one friend catch-up two weeks ahead (future you will thank you).", intensity: "low", tags: ["friendship","planning"] },
  { id: "relationships-044", domain: "relationships", text: "Write a list of 5 shared traditions you want to build.", intensity: "medium", tags: ["tradition","connection"] },
  { id: "relationships-045", domain: "relationships", text: "Send a message that asks a real question (not 'how are you').", intensity: "low", tags: ["connection","conversation"] },
  { id: "relationships-046", domain: "relationships", text: "Do a tiny 'life admin' sync: money, calendar, next month.", intensity: "high", tags: ["planning","alignment"] },
  { id: "relationships-047", domain: "relationships", text: "Write down one thing you assume about them and verify it.", intensity: "medium", tags: ["assumptions","clarity"] },
  { id: "relationships-048", domain: "relationships", text: "Pick one relationship you want to invest in and set one action.", intensity: "medium", tags: ["priority","actions"] },
  { id: "relationships-049", domain: "relationships", text: "Ask: 'What’s one thing you want us to improve together?'", intensity: "high", tags: ["growth","team"] },
  { id: "relationships-050", domain: "relationships", text: "Create a shared note for 'things we want to do' (dates, trips, goals).", intensity: "low", tags: ["planning","fun"] },
  { id: "relationships-051", domain: "relationships", text: "Write a 'repair ritual' plan for after a fight (2 steps).", intensity: "high", tags: ["repair","systems"] },
  { id: "relationships-052", domain: "relationships", text: "Send one photo memory and say why it matters to you.", intensity: "low", tags: ["connection","meaning"] },
  { id: "relationships-053", domain: "relationships", text: "Name one topic you avoid and why (then decide a safer way to start).", intensity: "high", tags: ["courage","communication"] },
  { id: "relationships-054", domain: "relationships", text: "Do a small gesture that matches their preferences (not yours).", intensity: "medium", tags: ["love-language","care"] },
  { id: "relationships-055", domain: "relationships", text: "Write a short gratitude list about a person you take for granted.", intensity: "medium", tags: ["gratitude","awareness"] },
  { id: "relationships-056", domain: "relationships", text: "Ask: 'Want advice or just a listening ear?'", intensity: "low", tags: ["communication","support"] },
  { id: "relationships-057", domain: "relationships", text: "Make one plan to reduce a recurring stress in the household.", intensity: "high", tags: ["ops","alignment"] },
  { id: "relationships-058", domain: "relationships", text: "Write a 3-line message to reconnect with someone you miss.", intensity: "medium", tags: ["reconnect","friendship"] },
  { id: "relationships-059", domain: "relationships", text: "Pick one boundary and practice saying it out loud once.", intensity: "high", tags: ["boundaries","confidence"] },
  { id: "relationships-060", domain: "relationships", text: "Ask: 'What does a good weekend look like for you?'", intensity: "low", tags: ["planning","connection"] },
  { id: "relationships-061", domain: "relationships", text: "Plan one mini-date at home (music, snacks, no screens).", intensity: "low", tags: ["date","connection"] },
  { id: "relationships-062", domain: "relationships", text: "Write a small 'support menu' for yourself and share it.", intensity: "high", tags: ["needs","clarity"] },
  { id: "relationships-063", domain: "relationships", text: "Pick one person to forgive a little today (including yourself).", intensity: "high", tags: ["repair","mindset"] },
  { id: "relationships-064", domain: "relationships", text: "Ask: 'What’s one thing you’re proud of lately?'", intensity: "low", tags: ["connection","affirmation"] },
  { id: "relationships-065", domain: "relationships", text: "Do a 'future planning' chat: next 3 months, one goal, one trip, one habit.", intensity: "high", tags: ["planning","alignment"] },

  ],
  dating: [
    { id: "dating-001", domain: "dating", text: "Write a one-line opener about something in their profile." },
    { id: "dating-002", domain: "dating", text: "Swap your first photo for a clearer, brighter one." },
    { id: "dating-003", domain: "dating", text: "Add one specific hobby to your bio." },
    { id: "dating-004", domain: "dating", text: "Draft a simple coffee date invite." },
    { id: "dating-005", domain: "dating", text: "Send a short follow-up message to a recent match." },
    { id: "dating-006", domain: "dating", text: "Choose a low-pressure first date idea." },
    { id: "dating-007", domain: "dating", text: "Write a kind boundary you want to keep." },
    { id: "dating-008", domain: "dating", text: "Pick two photos that show your typical weekend." },
    { id: "dating-009", domain: "dating", text: "Prepare one good question to ask on a date." },
    { id: "dating-010", domain: "dating", text: "Update your bio to say what you are actually looking for." },
    { id: "dating-011", domain: "dating", text: "Write a playful but respectful opener template." },
    { id: "dating-012", domain: "dating", text: "Plan a walk-and-talk date route." },
    { id: "dating-013", domain: "dating", text: "List three non-negotiables for your dating life." },
    { id: "dating-014", domain: "dating", text: "Send a short thank-you text after a good date." },
    { id: "dating-015", domain: "dating", text: "Pick a nearby spot for a first meetup." },
    { id: "dating-016", domain: "dating", text: "Refresh your prompt answers with more specific details." },
    { id: "dating-017", domain: "dating", text: "Write a polite \"not-a-match\" message you can reuse." },
    { id: "dating-018", domain: "dating", text: "Choose one green flag you want to notice early." },
    { id: "dating-019", domain: "dating", text: "Draft a simple plan for a second date." },
    { id: "dating-020", domain: "dating", text: "Identify one habit that keeps you from messaging back." },
    { id: "dating-021", domain: "dating", text: "Remove one vague line from your bio." },
    { id: "dating-022", domain: "dating", text: "Write a quick message that suggests a time and place." },
    { id: "dating-023", domain: "dating", text: "Add one photo that shows you with friends or family." },
    { id: "dating-024", domain: "dating", text: "Set a clear intention for your next date." },
    { id: "dating-025", domain: "dating", text: "Pick one topic you want to ask about beyond small talk." },
     { id: "dating-026", domain: "dating", text: "Rewrite one prompt answer to include a specific story (one sentence).", intensity: "low", tags: ["profile","clarity"] },
  { id: "dating-027", domain: "dating", text: "Pick one photo and write a caption-worthy context you can mention.", intensity: "low", tags: ["profile","conversation"] },
  { id: "dating-028", domain: "dating", text: "Message a match with a question that has two options to choose from.", intensity: "low", tags: ["messaging","ease"] },
  { id: "dating-029", domain: "dating", text: "Decide your first-date budget cap and stick to it.", intensity: "medium", tags: ["boundaries","money"] },
  { id: "dating-030", domain: "dating", text: "Write a soft exit line for when the vibe isn’t there.", intensity: "medium", tags: ["boundaries","communication"] },
  { id: "dating-031", domain: "dating", text: "Pick a 'go-to' first date plan: place, time, backup option.", intensity: "medium", tags: ["planning","logistics"] },
  { id: "dating-032", domain: "dating", text: "Write 3 green flags you want to see early.", intensity: "medium", tags: ["clarity","standards"] },
  { id: "dating-033", domain: "dating", text: "Write 3 red flags you will not ignore.", intensity: "high", tags: ["boundaries","standards"] },
  { id: "dating-034", domain: "dating", text: "Replace one 'vague' bio line with a concrete preference.", intensity: "low", tags: ["profile","clarity"] },
  { id: "dating-035", domain: "dating", text: "Write a second-date suggestion template that’s confident and simple.", intensity: "low", tags: ["messaging","planning"] },
  { id: "dating-036", domain: "dating", text: "Ask a match: 'What’s your ideal low-key weekend?'", intensity: "low", tags: ["conversation","compatibility"] },
  { id: "dating-037", domain: "dating", text: "Write one boundary for physical pace and how you’ll communicate it.", intensity: "high", tags: ["boundaries","safety"] },
  { id: "dating-038", domain: "dating", text: "Pick one day to swipe/message (timeboxed) so it doesn’t eat your week.", intensity: "medium", tags: ["habits","timeboxing"] },
  { id: "dating-039", domain: "dating", text: "Write a 3-line 'nice to meet you' follow-up for after the date.", intensity: "low", tags: ["follow-up","communication"] },
  { id: "dating-040", domain: "dating", text: "Choose one prompt that shows values, not hobbies.", intensity: "medium", tags: ["profile","values"] },
  { id: "dating-041", domain: "dating", text: "Write one honest line about what you’re looking for (no waffle).", intensity: "medium", tags: ["clarity","intent"] },
  { id: "dating-042", domain: "dating", text: "Plan a date that’s mostly walking (less awkward, more flow).", intensity: "low", tags: ["date","planning"] },
  { id: "dating-043", domain: "dating", text: "Write 5 'easy questions' for dates when conversation dips.", intensity: "medium", tags: ["conversation","prep"] },
  { id: "dating-044", domain: "dating", text: "Pick a public, safe meetup default and save it in your notes.", intensity: "medium", tags: ["safety","planning"] },
  { id: "dating-045", domain: "dating", text: "Update one photo to show your face clearly (no sunglasses).", intensity: "low", tags: ["profile","photos"] },
  { id: "dating-046", domain: "dating", text: "Write a 'this week is hectic' message that keeps momentum.", intensity: "low", tags: ["messaging","honesty"] },
  { id: "dating-047", domain: "dating", text: "Write a polite 'I’m not feeling it' message you can actually send.", intensity: "high", tags: ["boundaries","closure"] },
  { id: "dating-048", domain: "dating", text: "Pick one spot for a first date that’s easy to leave if needed.", intensity: "medium", tags: ["safety","planning"] },
  { id: "dating-049", domain: "dating", text: "Write 3 lines you won’t tolerate in messages (and what you’ll do).", intensity: "high", tags: ["boundaries","standards"] },
  { id: "dating-050", domain: "dating", text: "Replace one selfie with a photo someone else took (more trust).", intensity: "low", tags: ["profile","photos"] },
  { id: "dating-051", domain: "dating", text: "Write a message that sets a plan: day + time + place (no pen pals).", intensity: "medium", tags: ["planning","messaging"] },
  { id: "dating-052", domain: "dating", text: "Pick one 'fun fact' about you and weave it into your bio.", intensity: "low", tags: ["profile","personality"] },
  { id: "dating-053", domain: "dating", text: "Decide your 'texting cadence' rule so you stop overthinking.", intensity: "medium", tags: ["habits","mindset"] },
  { id: "dating-054", domain: "dating", text: "Write a soft check-in after 48 hours: friendly, no pressure.", intensity: "low", tags: ["follow-up","messaging"] },
  { id: "dating-055", domain: "dating", text: "Choose one value you care about and ask a question that reveals it.", intensity: "medium", tags: ["compatibility","values"] },
  { id: "dating-056", domain: "dating", text: "Update your bio to remove anything that sounds bitter or defensive.", intensity: "medium", tags: ["profile","tone"] },
  { id: "dating-057", domain: "dating", text: "Write a plan for how you’ll debrief a date (1 minute, facts only).", intensity: "medium", tags: ["reflection","clarity"] },
  { id: "dating-058", domain: "dating", text: "Pick one 'date idea' that doesn’t involve alcohol.", intensity: "low", tags: ["date","ideas"] },
  { id: "dating-059", domain: "dating", text: "Write 3 signs you should walk away early (and trust it).", intensity: "high", tags: ["safety","boundaries"] },
  { id: "dating-060", domain: "dating", text: "Message someone you like with a compliment about taste, not looks.", intensity: "low", tags: ["messaging","respect"] },
  { id: "dating-061", domain: "dating", text: "Write a short line to set expectations: 'I’m keen to meet if we vibe.'", intensity: "medium", tags: ["clarity","intent"] },
  { id: "dating-062", domain: "dating", text: "Pick one awkward convo you avoid (kids, future, exclusivity) and draft your line.", intensity: "high", tags: ["communication","clarity"] },
  { id: "dating-063", domain: "dating", text: "Clean your chat list: unmatch/archive anything that’s dead energy.", intensity: "medium", tags: ["cleanup","focus"] },
  { id: "dating-064", domain: "dating", text: "Write a 'good morning' message that isn’t cringe: simple + specific.", intensity: "low", tags: ["messaging","tone"] },
  { id: "dating-065", domain: "dating", text: "Set a rule: no swiping when bored, only when intentional.", intensity: "high", tags: ["habits","mindset"] },

  ],
  lifestyle: [
    { id: "lifestyle-001", domain: "lifestyle", text: "Plan three simple meals for the week." },
    { id: "lifestyle-002", domain: "lifestyle", text: "Write a short bedtime routine checklist." },
    { id: "lifestyle-003", domain: "lifestyle", text: "Clear one surface in your living space." },
    { id: "lifestyle-004", domain: "lifestyle", text: "Pick a short walk route you can repeat." },
    { id: "lifestyle-005", domain: "lifestyle", text: "Review your subscriptions and cancel one you do not use." },
    { id: "lifestyle-006", domain: "lifestyle", text: "Create a grocery list based on what you already have." },
    { id: "lifestyle-007", domain: "lifestyle", text: "Set a realistic screen-time goal for tomorrow." },
    { id: "lifestyle-008", domain: "lifestyle", text: "Choose a workout you can finish in under 20 minutes." },
    { id: "lifestyle-009", domain: "lifestyle", text: "Pick one drawer to tidy." },
    { id: "lifestyle-010", domain: "lifestyle", text: "Set a spending limit for one category this week." },
    { id: "lifestyle-011", domain: "lifestyle", text: "Make a plan for when you will do laundry next." },
    { id: "lifestyle-012", domain: "lifestyle", text: "Write down your top three energy drains." },
    { id: "lifestyle-013", domain: "lifestyle", text: "Create a simple morning plan for tomorrow." },
    { id: "lifestyle-014", domain: "lifestyle", text: "Move your phone charger away from your bed." },
    { id: "lifestyle-015", domain: "lifestyle", text: "Set up a playlist for focused work or chores." },
    { id: "lifestyle-016", domain: "lifestyle", text: "Choose one habit you will track this week." },
    { id: "lifestyle-017", domain: "lifestyle", text: "Make a short list of errands to batch together." },
    { id: "lifestyle-018", domain: "lifestyle", text: "Write a quick budget check-in note for yourself." },
    { id: "lifestyle-019", domain: "lifestyle", text: "Plan a no-spend activity for the weekend." },
    { id: "lifestyle-020", domain: "lifestyle", text: "Pick one room to reset before sleep." },
    { id: "lifestyle-021", domain: "lifestyle", text: "Create a 5-item packing list you often need." },
    { id: "lifestyle-022", domain: "lifestyle", text: "Choose a simple stretch routine to do after waking." },
    { id: "lifestyle-023", domain: "lifestyle", text: "Write a note about what helps you fall asleep faster." },
    { id: "lifestyle-024", domain: "lifestyle", text: "Move one recurring task into your calendar." },
    { id: "lifestyle-025", domain: "lifestyle", text: "Pick one clutter hotspot to address this week." },
    { id: "lifestyle-026", domain: "lifestyle", text: "Pick one health habit and set the smallest possible version for tomorrow.", intensity: "medium", tags: ["habits","health"] },
  { id: "lifestyle-027", domain: "lifestyle", text: "Do a 10-minute 'reset sprint' in one room with a timer.", intensity: "low", tags: ["home","clean"] },
  { id: "lifestyle-028", domain: "lifestyle", text: "Write a 'minimum viable day' plan: 3 things only.", intensity: "medium", tags: ["planning","focus"] },
  { id: "lifestyle-029", domain: "lifestyle", text: "Pick a simple morning drink routine: water, coffee, electrolytes.", intensity: "low", tags: ["health","routine"] },
  { id: "lifestyle-030", domain: "lifestyle", text: "Create a 'Sunday list' of 5 prep tasks that make weekdays easier.", intensity: "medium", tags: ["planning","systems"] },
  { id: "lifestyle-031", domain: "lifestyle", text: "Write a short rule for bedtime: screens off at X.", intensity: "high", tags: ["sleep","boundaries"] },
  { id: "lifestyle-032", domain: "lifestyle", text: "Pick one body maintenance habit: stretch, walk, mobility (15 mins).", intensity: "low", tags: ["movement","health"] },
  { id: "lifestyle-033", domain: "lifestyle", text: "Do a 'money minute': check balance + one category.", intensity: "low", tags: ["money","awareness"] },
  { id: "lifestyle-034", domain: "lifestyle", text: "Create a 'friction list': 5 annoyances at home, fix one.", intensity: "medium", tags: ["home","improvement"] },
  { id: "lifestyle-035", domain: "lifestyle", text: "Write your 'default groceries' list (10 items you always need).", intensity: "low", tags: ["food","planning"] },
  { id: "lifestyle-036", domain: "lifestyle", text: "Pick one hobby you miss and schedule 20 minutes for it.", intensity: "medium", tags: ["joy","balance"] },
  { id: "lifestyle-037", domain: "lifestyle", text: "Set a 'phone parking' spot for evenings.", intensity: "medium", tags: ["focus","boundaries"] },
  { id: "lifestyle-038", domain: "lifestyle", text: "Pick one thing to donate or sell today (just one).", intensity: "low", tags: ["declutter","home"] },
  { id: "lifestyle-039", domain: "lifestyle", text: "Write a quick list of your top 3 stress signals.", intensity: "medium", tags: ["mental","awareness"] },
  { id: "lifestyle-040", domain: "lifestyle", text: "Plan a weekend micro-adventure (local, cheap, simple).", intensity: "medium", tags: ["fun","planning"] },
  { id: "lifestyle-041", domain: "lifestyle", text: "Create a 'default workout' you can do anywhere (10 mins).", intensity: "medium", tags: ["fitness","systems"] },
  { id: "lifestyle-042", domain: "lifestyle", text: "Write a list of 10 foods that make you feel good (and buy 2).", intensity: "low", tags: ["food","health"] },
  { id: "lifestyle-043", domain: "lifestyle", text: "Pick one health appointment/admin thing and book it.", intensity: "high", tags: ["admin","health"] },
  { id: "lifestyle-044", domain: "lifestyle", text: "Do a 15-minute 'digital tidy': desktop, downloads, screenshots.", intensity: "low", tags: ["digital","cleanup"] },
  { id: "lifestyle-045", domain: "lifestyle", text: "Write one line: 'What do I need less of this week?'", intensity: "medium", tags: ["reflection","focus"] },
  { id: "lifestyle-046", domain: "lifestyle", text: "Set one 'outside' habit: sunlight in eyes within 1 hour of waking.", intensity: "high", tags: ["health","routine"] },
  { id: "lifestyle-047", domain: "lifestyle", text: "Make a list of 5 tiny rewards that aren’t spending money.", intensity: "medium", tags: ["motivation","habits"] },
  { id: "lifestyle-048", domain: "lifestyle", text: "Create a 'night reset' checklist: 5 mins, same steps nightly.", intensity: "medium", tags: ["home","routine"] },
  { id: "lifestyle-049", domain: "lifestyle", text: "Pick one recurring expense and negotiate/cancel it.", intensity: "high", tags: ["money","ops"] },
  { id: "lifestyle-050", domain: "lifestyle", text: "Write your 'if I’m overwhelmed' playbook (3 steps).", intensity: "high", tags: ["mental","systems"] },
  { id: "lifestyle-051", domain: "lifestyle", text: "Pick one playlist for workouts and one for focus and save both.", intensity: "low", tags: ["mood","tools"] },
  { id: "lifestyle-052", domain: "lifestyle", text: "Do a 10-minute walk with no headphones (brain reset).", intensity: "low", tags: ["mental","movement"] },
  { id: "lifestyle-053", domain: "lifestyle", text: "Write a simple skincare routine you can actually maintain.", intensity: "medium", tags: ["self-care","routine"] },
  { id: "lifestyle-054", domain: "lifestyle", text: "Pick one relationship to nourish this week and plan it.", intensity: "medium", tags: ["connection","planning"] },
  { id: "lifestyle-055", domain: "lifestyle", text: "Do a 'kitchen reset': sink empty, benches clear, bin out.", intensity: "low", tags: ["home","clean"] },
  { id: "lifestyle-056", domain: "lifestyle", text: "Write a list of 5 things that recharge you (then do one).", intensity: "medium", tags: ["mental","energy"] },
  { id: "lifestyle-057", domain: "lifestyle", text: "Set a rule for caffeine cut-off time and stick to it tomorrow.", intensity: "high", tags: ["sleep","health"] },
  { id: "lifestyle-058", domain: "lifestyle", text: "Plan tomorrow’s lunch now (future you is grateful).", intensity: "low", tags: ["food","planning"] },
  { id: "lifestyle-059", domain: "lifestyle", text: "Pick one 'always messy' spot and add a container/system.", intensity: "medium", tags: ["home","systems"] },
  { id: "lifestyle-060", domain: "lifestyle", text: "Write one sentence: 'What does a good day look like for me?'", intensity: "medium", tags: ["reflection","clarity"] },
  { id: "lifestyle-061", domain: "lifestyle", text: "Do a 'closet scan': choose 3 outfits you can default to.", intensity: "low", tags: ["style","systems"] },
  { id: "lifestyle-062", domain: "lifestyle", text: "Set one hydration trigger: every coffee = one glass of water.", intensity: "medium", tags: ["health","habits"] },
  { id: "lifestyle-063", domain: "lifestyle", text: "Pick one thing you’re procrastinating and do the first 2 minutes.", intensity: "high", tags: ["execution","momentum"] },
  { id: "lifestyle-064", domain: "lifestyle", text: "Write a simple budget rule for the month (one line).", intensity: "medium", tags: ["money","rules"] },
  { id: "lifestyle-065", domain: "lifestyle", text: "Plan one intentional rest block this week (calendar it).", intensity: "high", tags: ["rest","planning"] },

  ],
  random: [
    { id: "random-001", domain: "random", text: "Rename five files in your Downloads folder." },
    { id: "random-002", domain: "random", text: "Close browser tabs you no longer need." },
    { id: "random-003", domain: "random", text: "Move three loose notes into a single doc." },
    { id: "random-004", domain: "random", text: "Create a one-line to-do for something you keep delaying." },
    { id: "random-005", domain: "random", text: "Pick a book you will read next and place it out." },
    { id: "random-006", domain: "random", text: "Delete screenshots you do not recognize." },
    { id: "random-007", domain: "random", text: "Start a \"maybe later\" list for ideas that are distracting you." },
    { id: "random-008", domain: "random", text: "Write a two-sentence summary of what you learned today." },
    { id: "random-009", domain: "random", text: "Pin your most-used note to the top." },
    { id: "random-010", domain: "random", text: "Choose one photo album to back up." },
    { id: "random-011", domain: "random", text: "Make a short list of places you want to visit nearby." },
    { id: "random-012", domain: "random", text: "Clean up your home screen by removing one app." },
    { id: "random-013", domain: "random", text: "Pick one saved link to archive or delete." },
    { id: "random-014", domain: "random", text: "Write a quick note about a problem you want to solve." },
    { id: "random-015", domain: "random", text: "Set a calendar reminder for something you keep forgetting." },
    { id: "random-016", domain: "random", text: "Make a small plan for a solo micro-adventure." },
    { id: "random-017", domain: "random", text: "Create a tiny checklist for your next trip." },
    { id: "random-018", domain: "random", text: "Organize one folder on your desktop." },
    { id: "random-019", domain: "random", text: "Write a quick thank-you note draft you can reuse." },
    { id: "random-020", domain: "random", text: "Pick one article to finish and delete the rest." },
    { id: "random-021", domain: "random", text: "Make a \"parking lot\" list for off-topic ideas." },
    { id: "random-022", domain: "random", text: "Choose one playlist to update or delete." },
    { id: "random-023", domain: "random", text: "Write a single sentence about your current mood." },
    { id: "random-024", domain: "random", text: "Sort your starred items and unstar two." },
    { id: "random-025", domain: "random", text: "Pick a small area to declutter for a fresh start." },
     { id: "random-026", domain: "random", text: "Write a list of 5 'tiny upgrades' you can do in your space today.", intensity: "low", tags: ["home","quickwins"] },
  { id: "random-027", domain: "random", text: "Pick one email thread and close it out with a final decision.", intensity: "medium", tags: ["admin","closure"] },
  { id: "random-028", domain: "random", text: "Make a list of 10 ideas you’ve had before (no judging).", intensity: "medium", tags: ["ideation","capture"] },
  { id: "random-029", domain: "random", text: "Do a 10-minute 'photo cleanup' (delete 20, favourite 5).", intensity: "low", tags: ["digital","cleanup"] },
  { id: "random-030", domain: "random", text: "Pick one app you don’t use and delete it.", intensity: "low", tags: ["digital","minimalism"] },
  { id: "random-031", domain: "random", text: "Write one 'rule' that would improve your next week.", intensity: "medium", tags: ["systems","clarity"] },
  { id: "random-032", domain: "random", text: "Pick one folder and rename it properly (future you wins).", intensity: "low", tags: ["digital","organisation"] },
  { id: "random-033", domain: "random", text: "Create a 5-item 'emergency kit' checklist for your car/bag.", intensity: "medium", tags: ["planning","safety"] },
  { id: "random-034", domain: "random", text: "Write a 3-line message to someone you respect (no agenda).", intensity: "medium", tags: ["connection","network"] },
  { id: "random-035", domain: "random", text: "Pick one recurring worry and write the next concrete step.", intensity: "high", tags: ["anxiety","action"] },
  { id: "random-036", domain: "random", text: "Choose one drawer and make it 80% empty (donate/bin).", intensity: "medium", tags: ["declutter","home"] },
  { id: "random-037", domain: "random", text: "Make a list of 5 'future you' favours you can do today.", intensity: "medium", tags: ["habits","planning"] },
  { id: "random-038", domain: "random", text: "Write a one-sentence 'what matters right now' statement.", intensity: "high", tags: ["clarity","focus"] },
  { id: "random-039", domain: "random", text: "Pick one notification category and turn it off.", intensity: "low", tags: ["focus","digital"] },
  { id: "random-040", domain: "random", text: "Do a 15-minute 'inbox sweep' and archive anything old noise.", intensity: "medium", tags: ["admin","cleanup"] },
  { id: "random-041", domain: "random", text: "Write a list of 10 things you’re grateful for (fast, no poetry).", intensity: "medium", tags: ["mindset","gratitude"] },
  { id: "random-042", domain: "random", text: "Pick one 'someday' task and schedule it (or delete it).", intensity: "high", tags: ["decisions","planning"] },
  { id: "random-043", domain: "random", text: "Create a 'default response' to common requests (save time).", intensity: "medium", tags: ["systems","templates"] },
  { id: "random-044", domain: "random", text: "Write a tiny list: '3 things I want to remember from today.'", intensity: "low", tags: ["reflection","memory"] },
  { id: "random-045", domain: "random", text: "Pick one area to make nicer: candle, lighting, tidy, scent.", intensity: "low", tags: ["home","vibes"] },
  { id: "random-046", domain: "random", text: "Make a 'no-buy' list for the next week (3 items).", intensity: "high", tags: ["money","discipline"] },
  { id: "random-047", domain: "random", text: "Pick one uncomfortable task and do the first email/message only.", intensity: "high", tags: ["execution","momentum"] },
  { id: "random-048", domain: "random", text: "Write a list of 5 things you want to learn this year.", intensity: "medium", tags: ["learning","vision"] },
  { id: "random-049", domain: "random", text: "Choose one 'default outfit' and prep it for tomorrow.", intensity: "low", tags: ["prep","systems"] },
  { id: "random-050", domain: "random", text: "Clean your notes app: delete 10 junk notes.", intensity: "low", tags: ["digital","cleanup"] },
  { id: "random-051", domain: "random", text: "Pick one corner of your space and make it photogenic.", intensity: "medium", tags: ["home","reset"] },
  { id: "random-052", domain: "random", text: "Write a one-page 'things I’m saying no to' list.", intensity: "high", tags: ["boundaries","focus"] },
  { id: "random-053", domain: "random", text: "Pick one thing you keep postponing and decide: do / delegate / delete.", intensity: "high", tags: ["decisions","clarity"] },
  { id: "random-054", domain: "random", text: "Do a 10-minute 'wallet clean': subscriptions, cards, receipts.", intensity: "medium", tags: ["money","admin"] },
  { id: "random-055", domain: "random", text: "Write 5 'micro joys' you can do in 5 minutes each.", intensity: "low", tags: ["joy","mental"] },
  { id: "random-056", domain: "random", text: "Pick one saved post/video and either act on it or unsave it.", intensity: "medium", tags: ["digital","cleanup"] },
  { id: "random-057", domain: "random", text: "Write the next 3 steps for your biggest goal (just steps).", intensity: "high", tags: ["planning","execution"] },
  { id: "random-058", domain: "random", text: "Pick one thing you can simplify in your routine (remove a step).", intensity: "medium", tags: ["simplicity","systems"] },
  { id: "random-059", domain: "random", text: "Create a '5-minute reset' ritual you can repeat daily.", intensity: "medium", tags: ["habits","systems"] },
  { id: "random-060", domain: "random", text: "Write a list of 5 people you want to learn from and why.", intensity: "medium", tags: ["network","learning"] },
  { id: "random-061", domain: "random", text: "Pick one tiny fear and do a small exposure step.", intensity: "high", tags: ["courage","growth"] },
  { id: "random-062", domain: "random", text: "Write one sentence: 'What would I do if I trusted myself more?'", intensity: "high", tags: ["mindset","reflection"] },
  { id: "random-063", domain: "random", text: "Do a 10-minute 'link cleanup': bookmarks, saved posts, reading list.", intensity: "low", tags: ["digital","cleanup"] },
  { id: "random-064", domain: "random", text: "Pick one item you own that annoys you and replace/fix it (research only).", intensity: "medium", tags: ["home","quality"] },
  { id: "random-065", domain: "random", text: "Write a list of 3 promises to yourself for the next 7 days.", intensity: "high", tags: ["commitment","habits"] },
  ],
};
