export type Domain =
  | "business"
  | "career"
  | "relationships"
  | "dating"
  | "lifestyle"
  | "random";

export type SparkPrompt = {
  id: string;
  domain: Domain;
  text: string;
  intensity?: "low" | "medium" | "high";
  tags?: string[];
};

export const sparkConstraints = [
  "15 minutes only",
  "10-minute timer",
  "limit to 3 items",
  "one pass only",
  "no new tools",
  "no money spent",
  "before lunch",
  "before dinner",
  "keep it to 5 bullets",
  "no phone",
  "stop at 20 minutes",
  "do it in one sitting",
];

export const sparkLibrary: Record<Domain, SparkPrompt[]> = {
  business: [
    { id: "business-001", domain: "business", text: "Rewrite your pricing page headline to name the specific outcome." },
    { id: "business-002", domain: "business", text: "List the top 5 objections from recent sales calls." },
    { id: "business-003", domain: "business", text: "Draft a 3-step onboarding email sequence." },
    { id: "business-004", domain: "business", text: "Pick one churned customer and write why they left." },
    { id: "business-005", domain: "business", text: "Create a one-sentence offer for your homepage hero." },
    { id: "business-006", domain: "business", text: "Outline a 5-slide product demo flow." },
    { id: "business-007", domain: "business", text: "Review the last 10 support tickets and tag the top theme." },
    { id: "business-008", domain: "business", text: "Write a follow-up email to a stalled lead." },
    { id: "business-009", domain: "business", text: "Define success metrics for your next experiment." },
    { id: "business-010", domain: "business", text: "Trim one step from your checkout flow." },
    { id: "business-011", domain: "business", text: "Map the first 3 minutes of user activation." },
    { id: "business-012", domain: "business", text: "Update your FAQ with the most common pre-sale question." },
    { id: "business-013", domain: "business", text: "Write a short case study intro for a happy customer." },
    { id: "business-014", domain: "business", text: "Identify one upsell opportunity in your current plan." },
    { id: "business-015", domain: "business", text: "Draft a weekly pipeline review checklist." },
    { id: "business-016", domain: "business", text: "Create a simple win-back message for past customers." },
    { id: "business-017", domain: "business", text: "Sketch a 2-minute product walkthrough script." },
    { id: "business-018", domain: "business", text: "List the top 3 referral sources from this month." },
    { id: "business-019", domain: "business", text: "Write a clear refund policy sentence." },
    { id: "business-020", domain: "business", text: "Decide the next pricing test you will run." },
    { id: "business-021", domain: "business", text: "Summarize your product in 10 words." },
    { id: "business-022", domain: "business", text: "Pick one feature to de-emphasize on your website." },
    { id: "business-023", domain: "business", text: "Write the opening line for a partner outreach email." },
    { id: "business-024", domain: "business", text: "Choose one KPI to review every Monday." },
    { id: "business-025", domain: "business", text: "Draft a checklist for first-time setup." },
  ],
  career: [
    { id: "career-001", domain: "career", text: "Add one quantified impact bullet to your resume." },
    { id: "career-002", domain: "career", text: "Write a two-sentence update for your manager." },
    { id: "career-003", domain: "career", text: "List three projects that show your strongest skills." },
    { id: "career-004", domain: "career", text: "Draft a short ask for feedback on your last project." },
    { id: "career-005", domain: "career", text: "Outline a promotion case with three outcomes you drove." },
    { id: "career-006", domain: "career", text: "Update your LinkedIn headline to match your target role." },
    { id: "career-007", domain: "career", text: "Identify one skill gap and a concrete next step to close it." },
    { id: "career-008", domain: "career", text: "Write a one-paragraph summary of a recent win." },
    { id: "career-009", domain: "career", text: "Create a one-page portfolio outline." },
    { id: "career-010", domain: "career", text: "Send a thank-you note to a mentor or teammate." },
    { id: "career-011", domain: "career", text: "Draft a meeting agenda for your next 1:1." },
    { id: "career-012", domain: "career", text: "List the top five companies you want to work for." },
    { id: "career-013", domain: "career", text: "Write a concise intro for a networking request." },
    { id: "career-014", domain: "career", text: "Review your calendar and block a focus window." },
    { id: "career-015", domain: "career", text: "Capture three metrics you can report in your next update." },
    { id: "career-016", domain: "career", text: "Draft a short story about solving a hard problem at work." },
    { id: "career-017", domain: "career", text: "Pick one project to de-scope and define the smaller win." },
    { id: "career-018", domain: "career", text: "Write a brief post about a lesson learned on the job." },
    { id: "career-019", domain: "career", text: "Create a checklist for your weekly review." },
    { id: "career-020", domain: "career", text: "List three people you should keep updated this week." },
    { id: "career-021", domain: "career", text: "Update one portfolio screenshot or case study image." },
    { id: "career-022", domain: "career", text: "Write a one-line summary of your current role." },
    { id: "career-023", domain: "career", text: "Draft a cold outreach note to a recruiter." },
    { id: "career-024", domain: "career", text: "Define success criteria for your next deliverable." },
    { id: "career-025", domain: "career", text: "List three meetings you can decline or shorten." },
  ],
  relationships: [
    { id: "relationships-001", domain: "relationships", text: "Ask your partner what would make next week easier." },
    { id: "relationships-002", domain: "relationships", text: "Send a short appreciation text to a close friend." },
    { id: "relationships-003", domain: "relationships", text: "Plan a low-key hangout with someone you miss." },
    { id: "relationships-004", domain: "relationships", text: "Write down one recurring tension and a gentle opener." },
    { id: "relationships-005", domain: "relationships", text: "Set a shared calendar reminder for a weekly check-in." },
    { id: "relationships-006", domain: "relationships", text: "Ask a family member how you can support them this month." },
    { id: "relationships-007", domain: "relationships", text: "Share one thing you appreciated about today." },
    { id: "relationships-008", domain: "relationships", text: "Name one small household task you will take over." },
    { id: "relationships-009", domain: "relationships", text: "Write a short apology note for a recent misstep." },
    { id: "relationships-010", domain: "relationships", text: "Bring up one decision that needs alignment soon." },
    { id: "relationships-011", domain: "relationships", text: "Plan a device-free meal with someone you live with." },
    { id: "relationships-012", domain: "relationships", text: "Ask a friend a question you have been avoiding." },
    { id: "relationships-013", domain: "relationships", text: "Choose one boundary you need to restate clearly." },
    { id: "relationships-014", domain: "relationships", text: "Send a simple \"thinking-of-you\" text to someone important." },
    { id: "relationships-015", domain: "relationships", text: "Schedule a short walk-and-talk with your partner." },
    { id: "relationships-016", domain: "relationships", text: "Write down one shared goal for the next month." },
    { id: "relationships-017", domain: "relationships", text: "Ask for clarification instead of assuming intent." },
    { id: "relationships-018", domain: "relationships", text: "Offer help on a task your roommate dislikes." },
    { id: "relationships-019", domain: "relationships", text: "Share one story about your day that invites response." },
    { id: "relationships-020", domain: "relationships", text: "Plan a low-cost activity you both enjoy." },
    { id: "relationships-021", domain: "relationships", text: "Write down one thing you want to celebrate together." },
    { id: "relationships-022", domain: "relationships", text: "Invite feedback on how you can communicate better." },
    { id: "relationships-023", domain: "relationships", text: "Pick one conversation to follow up on this week." },
    { id: "relationships-024", domain: "relationships", text: "Send a quick voice note to check in with a friend." },
    { id: "relationships-025", domain: "relationships", text: "Make a plan to reconnect with someone you drifted from." },
  ],
  dating: [
    { id: "dating-001", domain: "dating", text: "Write a one-line opener about something in their profile." },
    { id: "dating-002", domain: "dating", text: "Swap your first photo for a clearer, brighter one." },
    { id: "dating-003", domain: "dating", text: "Add one specific hobby to your bio." },
    { id: "dating-004", domain: "dating", text: "Draft a simple coffee date invite." },
    { id: "dating-005", domain: "dating", text: "Send a short follow-up message to a recent match." },
    { id: "dating-006", domain: "dating", text: "Choose a low-pressure first date idea." },
    { id: "dating-007", domain: "dating", text: "Write a kind boundary you want to keep." },
    { id: "dating-008", domain: "dating", text: "Pick two photos that show your typical weekend." },
    { id: "dating-009", domain: "dating", text: "Prepare one good question to ask on a date." },
    { id: "dating-010", domain: "dating", text: "Update your bio to say what you are actually looking for." },
    { id: "dating-011", domain: "dating", text: "Write a playful but respectful opener template." },
    { id: "dating-012", domain: "dating", text: "Plan a walk-and-talk date route." },
    { id: "dating-013", domain: "dating", text: "List three non-negotiables for your dating life." },
    { id: "dating-014", domain: "dating", text: "Send a short thank-you text after a good date." },
    { id: "dating-015", domain: "dating", text: "Pick a nearby spot for a first meetup." },
    { id: "dating-016", domain: "dating", text: "Refresh your prompt answers with more specific details." },
    { id: "dating-017", domain: "dating", text: "Write a polite \"not-a-match\" message you can reuse." },
    { id: "dating-018", domain: "dating", text: "Choose one green flag you want to notice early." },
    { id: "dating-019", domain: "dating", text: "Draft a simple plan for a second date." },
    { id: "dating-020", domain: "dating", text: "Identify one habit that keeps you from messaging back." },
    { id: "dating-021", domain: "dating", text: "Remove one vague line from your bio." },
    { id: "dating-022", domain: "dating", text: "Write a quick message that suggests a time and place." },
    { id: "dating-023", domain: "dating", text: "Add one photo that shows you with friends or family." },
    { id: "dating-024", domain: "dating", text: "Set a clear intention for your next date." },
    { id: "dating-025", domain: "dating", text: "Pick one topic you want to ask about beyond small talk." },
  ],
  lifestyle: [
    { id: "lifestyle-001", domain: "lifestyle", text: "Plan three simple meals for the week." },
    { id: "lifestyle-002", domain: "lifestyle", text: "Write a short bedtime routine checklist." },
    { id: "lifestyle-003", domain: "lifestyle", text: "Clear one surface in your living space." },
    { id: "lifestyle-004", domain: "lifestyle", text: "Pick a short walk route you can repeat." },
    { id: "lifestyle-005", domain: "lifestyle", text: "Review your subscriptions and cancel one you do not use." },
    { id: "lifestyle-006", domain: "lifestyle", text: "Create a grocery list based on what you already have." },
    { id: "lifestyle-007", domain: "lifestyle", text: "Set a realistic screen-time goal for tomorrow." },
    { id: "lifestyle-008", domain: "lifestyle", text: "Choose a workout you can finish in under 20 minutes." },
    { id: "lifestyle-009", domain: "lifestyle", text: "Pick one drawer to tidy." },
    { id: "lifestyle-010", domain: "lifestyle", text: "Set a spending limit for one category this week." },
    { id: "lifestyle-011", domain: "lifestyle", text: "Make a plan for when you will do laundry next." },
    { id: "lifestyle-012", domain: "lifestyle", text: "Write down your top three energy drains." },
    { id: "lifestyle-013", domain: "lifestyle", text: "Create a simple morning plan for tomorrow." },
    { id: "lifestyle-014", domain: "lifestyle", text: "Move your phone charger away from your bed." },
    { id: "lifestyle-015", domain: "lifestyle", text: "Set up a playlist for focused work or chores." },
    { id: "lifestyle-016", domain: "lifestyle", text: "Choose one habit you will track this week." },
    { id: "lifestyle-017", domain: "lifestyle", text: "Make a short list of errands to batch together." },
    { id: "lifestyle-018", domain: "lifestyle", text: "Write a quick budget check-in note for yourself." },
    { id: "lifestyle-019", domain: "lifestyle", text: "Plan a no-spend activity for the weekend." },
    { id: "lifestyle-020", domain: "lifestyle", text: "Pick one room to reset before sleep." },
    { id: "lifestyle-021", domain: "lifestyle", text: "Create a 5-item packing list you often need." },
    { id: "lifestyle-022", domain: "lifestyle", text: "Choose a simple stretch routine to do after waking." },
    { id: "lifestyle-023", domain: "lifestyle", text: "Write a note about what helps you fall asleep faster." },
    { id: "lifestyle-024", domain: "lifestyle", text: "Move one recurring task into your calendar." },
    { id: "lifestyle-025", domain: "lifestyle", text: "Pick one clutter hotspot to address this week." },
  ],
  random: [
    { id: "random-001", domain: "random", text: "Rename five files in your Downloads folder." },
    { id: "random-002", domain: "random", text: "Close browser tabs you no longer need." },
    { id: "random-003", domain: "random", text: "Move three loose notes into a single doc." },
    { id: "random-004", domain: "random", text: "Create a one-line to-do for something you keep delaying." },
    { id: "random-005", domain: "random", text: "Pick a book you will read next and place it out." },
    { id: "random-006", domain: "random", text: "Delete screenshots you do not recognize." },
    { id: "random-007", domain: "random", text: "Start a \"maybe later\" list for ideas that are distracting you." },
    { id: "random-008", domain: "random", text: "Write a two-sentence summary of what you learned today." },
    { id: "random-009", domain: "random", text: "Pin your most-used note to the top." },
    { id: "random-010", domain: "random", text: "Choose one photo album to back up." },
    { id: "random-011", domain: "random", text: "Make a short list of places you want to visit nearby." },
    { id: "random-012", domain: "random", text: "Clean up your home screen by removing one app." },
    { id: "random-013", domain: "random", text: "Pick one saved link to archive or delete." },
    { id: "random-014", domain: "random", text: "Write a quick note about a problem you want to solve." },
    { id: "random-015", domain: "random", text: "Set a calendar reminder for something you keep forgetting." },
    { id: "random-016", domain: "random", text: "Make a small plan for a solo micro-adventure." },
    { id: "random-017", domain: "random", text: "Create a tiny checklist for your next trip." },
    { id: "random-018", domain: "random", text: "Organize one folder on your desktop." },
    { id: "random-019", domain: "random", text: "Write a quick thank-you note draft you can reuse." },
    { id: "random-020", domain: "random", text: "Pick one article to finish and delete the rest." },
    { id: "random-021", domain: "random", text: "Make a \"parking lot\" list for off-topic ideas." },
    { id: "random-022", domain: "random", text: "Choose one playlist to update or delete." },
    { id: "random-023", domain: "random", text: "Write a single sentence about your current mood." },
    { id: "random-024", domain: "random", text: "Sort your starred items and unstar two." },
    { id: "random-025", domain: "random", text: "Pick a small area to declutter for a fresh start." },
  ],
};
